# Fix parameters
MEMORY_SIZE = 100000
BATCH_SIZE = 10
NUM_EPOCHS = 1000
MAX_NORM = 1000
LEARNING_RATE = 0.001
NUM_OF_PLAY_GAMES = 10
NUM_OF_EVAL_GAMES = 10
MAX_NUMBER_OF_MOVES = 200
INITIAL_EXPLORATION = 0.8
DECAY_FACTOR = 0.8

# Monte Carlo Tree Search Parameters for Training (Play Stage)
TRAINING_MCTS_SIMULATIONS = 50
TRAINING_MCTS_CPUCT = 1.2

# Monte Carlo Tree Search Parameters for Playing (Eval Stage)
EVAL_MCTS_SIMULATIONS = 25
EVAL_MCTS_CPUCT = 3