run:
	@export PYTHONPATH=$PYTHONPATH:$(pwd)
	@python omegazero.py

clean_games:
	@rm -rf games/*

clean_artifacts:
	@rm -rf artifacts/*

clean_log:
	@rm log.txt

clean: clean_games clean_artifacts clean_log